apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-devops
  template:
    metadata:
      labels:
        app: tp-devops
    spec:
      containers:
        - name: tp-devops
          image: elise259/td-devops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
      # Pull the private Docker image using this secret
      imagePullSecrets:
        - name: dockerhub-creds
---
apiVersion: v1
kind: Service
metadata:
  name: tp-devops-service
spec:
  type: NodePort
  selector:
    app: tp-devops
  ports:
    - port: 80
      targetPort: 3000
